[package]
name = "lucinda"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nalgebra = "0.33.1"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
rand = "0.8.5"
